# Importando as bibliotecas 

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import fashion_mnist

# Carregando a base de dados

In [2]:
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

4431872/4422102 [==============================] - 0s 0us/step


Imprimindo o X_train observamos que temos um cubo que contém várias imagens.

In [3]:
X_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

Imprimindo a primeira imagem observamos uma matriz

In [4]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,
          0,   0,  13,  73,   0,   0,   1,   4,   0,   0,   0,   0,   1,
          1,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
          0,  36, 136, 127,  62,  54,   0,   0,   0,   1,   3,   4,   0,
          0,   3],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,
          0, 102, 204, 176, 134, 144, 123,  23,   0,   0,   0,   0,  12,
         10,   0],
       [  

Imprimindo o y_train observamos que a saída tem multiplas classes.

In [5]:
y_train

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [6]:
y_train[0]

9

# Normalizando as Imagens

Para normalizar as imagens da base de treinamento e teste, dividimos cada pixel das imagens pelo maior valor que é 255. Com isso, os pixels estarão na faixa entre 0 e 1. Fazendo isso ganhamos velocidade no treinamento da rede neural.

In [9]:
X_train = X_train/255.0

X_test = X_test/255.0

In [10]:
X_train[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

# Remodelando.

Vamos mudar a dimensão das bases de dados para ficarem no formato de um vetor, pois estamos trabalhando com uma rde neural densa.

In [11]:
X_train.shape

(60000, 28, 28)

In [12]:
X_train = X_train.reshape(-1, 28*28)
X_train.shape

(60000, 784)

In [13]:
X_train[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [14]:
X_test = X_test.reshape(-1, 28*28)
X_test.shape

(10000, 784)

# Construindo a Rede Neural

In [15]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(units=128, activation='relu', input_shape=(784,)))
model.add(tf.keras.layers.Dropout(0.2))

model.add(tf.keras.layers.Dense(units=10, activation='softmax'))

Compilando o modelo

In [16]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['sparse_categorical_accuracy'])

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               100480    
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


# Treinando o Modelo

In [18]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.5362 - sparse_categorical_accuracy: 0.8102
Epoch 2/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4031 - sparse_categorical_accuracy: 0.8535
Epoch 3/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3678 - sparse_categorical_accuracy: 0.8660
Epoch 4/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3472 - sparse_categorical_accuracy: 0.8726
Epoch 5/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3313 - sparse_categorical_accuracy: 0.8789
Epoch 6/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3200 - sparse_categorical_accuracy: 0.8826
Epoch 7/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3080 - sparse_categorical_accuracy: 0.8859
Epoch 8/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3008 - sparse_categorical_accuracy: 0.8868
Epoch 9/10
1875/1875 [==========

# Avaliação do Modelo e previsão

In [19]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)

313/313 [==============================] - 1s 1ms/step - loss: 0.3540 - sparse_categorical_accuracy: 0.8717


In [20]:
test_loss, test_accuracy = model.evaluate(X_train, y_train)

1875/1875 [==============================] - 3s 2ms/step - loss: 0.2557 - sparse_categorical_accuracy: 0.9032


In [34]:
p = model.predict(X_test)

In [35]:
p[0]

array([2.4856474e-06, 3.4149031e-07, 1.3740524e-08, 1.7813809e-06,
       1.0250044e-07, 1.0505389e-02, 1.1316130e-06, 4.5993593e-02,
       2.0762341e-06, 9.4349313e-01], dtype=float32)

In [36]:
np.argmax(p[0])

9

Examinando y_teste, vemos que essa classificação é correta:

In [37]:
y_test[0]

9