# Importando as Bibliotecas

In [ ]:
import tensorflow as tf
import pandas as pd
import numpy as np

# Importando e organizando os Dados com Pandas 

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
iris = load_iris()
iris_df = pd.DataFrame(data = iris.data, columns = iris.feature_names)
iris_df['label'] = iris.target
iris_df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)

In [ ]:
iris_df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label,species
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa


In [ ]:
X = iris.data
y = iris.target

In [ ]:
from tensorflow.keras.utils import to_categorical

In [ ]:
y = to_categorical(y)
print(y[0])
print(y[50])
print(y[100])

[1. 0. 0.]
[0. 1. 0.]
[0. 0. 1.]


# Validação Cruzada

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state = 123)

print('X_train.shape',X_train.shape)
print('y_train.shape', y_train.shape)
print('X_test.shape', X_test.shape)
print('y_test.shape', y_test.shape)

X_train.shape (90, 4)
y_train.shape (90, 3)
X_test.shape (60, 4)
y_test.shape (60, 3)


# Normalização dos Dados

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

# Criando o Modelo

In [ ]:
model = tf.keras.models.Sequential()
model.add(tf.keras.Input(shape=(4,)))
model.add(tf.keras.layers.Dense(3, kernel_initializer='zeros'))
model.add(tf.keras.layers.Activation('sigmoid'))

model.compile(loss= 'categorical_crossentropy', optimizer='sgd', metrics=['categorical_accuracy'])

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 15        
                                                                 
 activation (Activation)     (None, 3)                 0         
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


# Treinando o Modelo

In [ ]:
model.fit(X_train, y_train, epochs=10, batch_size=5, verbose=1)

Epoch 1/10
18/18 [==============================] - 1s 2ms/step - loss: 1.0311 - categorical_accuracy: 0.6556
Epoch 2/10
18/18 [==============================] - 0s 1ms/step - loss: 0.9131 - categorical_accuracy: 0.7778
Epoch 3/10
18/18 [==============================] - 0s 1ms/step - loss: 0.8285 - categorical_accuracy: 0.7778
Epoch 4/10
18/18 [==============================] - 0s 1ms/step - loss: 0.7648 - categorical_accuracy: 0.8111
Epoch 5/10
18/18 [==============================] - 0s 2ms/step - loss: 0.7173 - categorical_accuracy: 0.8111
Epoch 6/10
18/18 [==============================] - 0s 1ms/step - loss: 0.6799 - categorical_accuracy: 0.8111
Epoch 7/10
18/18 [==============================] - 0s 2ms/step - loss: 0.6496 - categorical_accuracy: 0.8222
Epoch 8/10
18/18 [==============================] - 0s 2ms/step - loss: 0.6247 - categorical_accuracy: 0.8222
Epoch 9/10
18/18 [==============================] - 0s 1ms/step - loss: 0.6036 - categorical_accuracy: 0.8222
Epoch 10/1

# Teste do Modelo

In [ ]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 10ms/step - loss: 0.4923 - categorical_accuracy: 0.9167


In [ ]:
y_test_pred = model.predict(X_test)
print(y_test_pred)

[[0.27210817 0.6243769  0.616752  ]
 [0.21894747 0.5747405  0.72523737]
 [0.20761588 0.6013644  0.7167106 ]
 [0.47302198 0.5379075  0.48902568]
 [0.85670096 0.40017053 0.20046344]
 [0.33840346 0.55599415 0.60956806]
 [0.28862745 0.64265466 0.5781429 ]
 [0.841041   0.45150015 0.1867325 ]
 [0.8083757  0.49509    0.19468507]
 [0.4109354  0.5950779  0.49377587]
 [0.22221455 0.5593061  0.7338923 ]
 [0.87314385 0.32745153 0.22982275]
 [0.45628926 0.57537574 0.46791214]
 [0.26729617 0.56857127 0.6753229 ]
 [0.13773867 0.59167904 0.8120353 ]
 [0.21674418 0.5771156  0.72587585]
 [0.8140149  0.41876882 0.24076638]
 [0.8406965  0.47515777 0.17307791]
 [0.36743975 0.56460035 0.5703704 ]
 [0.7878978  0.48553368 0.22193614]
 [0.81652236 0.43136546 0.22852135]
 [0.30456656 0.58611345 0.61721027]
 [0.8208879  0.43410066 0.22145021]
 [0.32543233 0.55803174 0.6214577 ]
 [0.85257745 0.37834805 0.22125024]
 [0.79465693 0.4366279  0.25004557]
 [0.7849268  0.43669713 0.2611434 ]
 [0.312168   0.58416694 0.61

# Pesos e bias 

In [ ]:
print(model.get_weights()[0])
print(model.get_weights()[1])

[[-0.2895654   0.02711597  0.26244944]
 [ 0.28041884 -0.23403065 -0.04638813]
 [-0.39508083  0.08530226  0.30977854]
 [-0.37988287  0.03685512  0.34302783]]
[-0.06800741  0.11169144 -0.04368398]
